"use client";
import { onAuthStateChanged } from "firebase/auth";
import "./globals.css";
import { Session } from "next-auth";
import { Inter } from "next/font/google";

import { AuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import firebase from "@/lib/firebase/firebase";

import { auth as firebaseAuth } from "@/lib/firebase/config";
import MainLayout from "@/layouts/MainLayout";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const auth = firebaseAuth;
  onAuthStateChanged(auth, (user) => {
    console.log(user);
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <MainLayout>{children}</MainLayout>
        </AuthContextProvider>
      </body>
    </html>
  );
}
